baseURL = "https://lcroberts.dev/"
title = "lcroberts"
author = "Logan Roberts"
copyright = "Logan Roberts"
paginate = 10
languageCode = "en"
theme = "tailwind"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "/blog"
    weight = 0

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 10

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume.pdf"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
