baseURL = 'https://lcroberts.dev/'
languageCode = 'en-us'
title = 'lcroberts'
copyright = "Logan Roberts"
summaryLength = 30

[taxonomies]
category = "categories"
tag = "tags"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
    wrapperClass = 'highlight'

[params]
  author = ['Logan Roberts']
  copyright_from = '2022'

[menus]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pageRef = "/blog"
    weight = 2

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
  [[build.cachebusters]]
    source = 'assets/.*\.(js|ts|jsx|tsx|scss)'
    target = '(js|css)'
  [[build.cachebusters]]
    source = 'assets/.*\.(.*)$'
    target = '$1'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/bootstrap-icons/font/fonts"
    target = "static/css/fonts"
  [[module.mounts]]
    source = "node_modules/bootstrap-icons/"
    target = "assets/css/bootstrap-icons"
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
