name: ollama-webui

services:
  ollama:
    image: ollama/ollama:rocm
    volumes:
      - ./ollama:/root/.ollama
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: http://searxng:8080/search?q=<query>
    ports:
      - 3000:8080
    volumes:
      - ./open-webui:/app/backend/data

  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng
